import {z} from 'zod';
const text=z.string().trim().max(2000);
const short=z.string().trim().max(240);
export const date=z.union([z.literal(''),z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'Use a real date')]);
const url=z.union([z.literal(''),z.string().url().max(2000).refine(v=>{const u=new URL(v);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password;})]);
export const productKey=z.object({year:z.string().regex(/^(\d{4})?$/),set:short,sport:short,format:short}).strict();
export const product=productKey.extend({status:z.enum(['carried','incoming','watching','unavailable']),evidence:url,confirmedAt:date,notes:text}).strict().superRefine((v,c)=>{if(['carried','incoming'].includes(v.status)&&(!v.year||!v.set||!v.sport||!v.format||!v.evidence||!v.confirmedAt))c.addIssue({code:'custom',message:'Carried or incoming products need exact year, set, sport, format, evidence and confirmation date.'});});
export const detail=z.object({product:productKey,topic:z.enum(['story','release','checklist','delay','official announcement','chase','pull','sale','event']),certainty:z.enum(['incomplete','rumor','reported','confirmed']),evidence:url,region:short,manufacturerDate:date,manufacturerSource:url,arrivalDate:date,arrivalSource:url,card:short,player:short,parallel:short,numbering:short,eligibleFormats:short,pullStatus:z.enum(['unknown','reported pulled','confirmed pulled','reported unpulled']),pullEvidence:url,pullAsOf:date,saleType:z.enum(['unknown','asking','completed']),price:z.union([z.literal(''),z.string().regex(/^\d+(\.\d{1,2})?$/)]),currency:z.string().regex(/^([A-Z]{3})?$/),saleDate:date,grade:short,buyerPremium:z.enum(['unknown','included','excluded','not applicable']),notes:text}).strict().superRefine((v,c)=>{if((v.manufacturerDate&&!v.manufacturerSource)||(v.arrivalDate&&!v.arrivalSource))c.addIssue({code:'custom',message:'Each release or arrival date needs its own source.'});if(v.pullStatus!=='unknown'&&(!v.pullEvidence||!v.pullAsOf))c.addIssue({code:'custom',message:'Reported pull status needs dated evidence.'});if(v.certainty==='confirmed'&&!v.evidence)c.addIssue({code:'custom',message:'Confirmed information needs evidence.'});});
export const queue=z.object({itemId:z.string().max(100),title:short.min(1),state:z.enum(['Saved','Draft','Needs review','Approved','Archived']),assignee:z.string().max(100),notes:text,facebook:z.string().max(5000),instagram:z.string().max(3000),reel:z.string().max(4000),references:z.array(url.refine(Boolean)).max(20),cta:short,original:z.enum(['none','customer pull','staff pick','break highlight','grading return','Boomski clip']),assetId:z.string().max(100),assetOwner:z.string().max(200),attribution:short,permission:z.enum(['unknown','owned','granted','denied']),permissionEvidence:text,calendarDate:z.union([z.literal(''),z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v+'Z'))&&new Date(v+'Z').toISOString().slice(0,16)===v,'Use a real calendar date and time')]),calendarChannel:z.enum(['facebook','instagram'])}).strict();
export const team=z.object({name:short.min(1),email:z.string().email().optional(),title:short,role:z.enum(['admin','staff']),userId:z.string().max(200),active:z.boolean()}).strict();
export const schemas={product,detail,queue,team};
export const editCommand=z.object({kind:z.enum(['product','detail','queue','team']),id:z.string().min(1).max(100),version:z.number().int().nonnegative(),data:z.unknown()}).strict();
export type Detail=z.infer<typeof detail>;export type Product=z.infer<typeof product>;export type Queue=z.infer<typeof queue>;export type Team=z.infer<typeof team>;
export type RecordRow={id:string;kind:keyof typeof schemas;data:unknown;version:number;updated_at:string};
export const blankDetail:Detail={product:{year:'',set:'',sport:'',format:''},topic:'story',certainty:'incomplete',evidence:'',region:'',manufacturerDate:'',manufacturerSource:'',arrivalDate:'',arrivalSource:'',card:'',player:'',parallel:'',numbering:'',eligibleFormats:'',pullStatus:'unknown',pullEvidence:'',pullAsOf:'',saleType:'unknown',price:'',currency:'',saleDate:'',grade:'',buyerPremium:'unknown',notes:''};
export const blankQueue:Queue={itemId:'',title:'',state:'Saved',assignee:'',notes:'',facebook:'',instagram:'',reel:'',references:[],cta:'What would you add to your collection? Talk cards with Northside.',original:'none',assetId:'',assetOwner:'',attribution:'',permission:'unknown',permissionEvidence:'',calendarDate:'',calendarChannel:'facebook'};
export const roster=[['steve','Steve','Admin','admin'],['joey','Joey','CEO','staff'],['brody','Brody','Consignment manager','staff'],['zach','Zach','Breaker/Co-Owner','staff'],['nick','Nick','Store Manager','staff'],['nik','Nik','Sales Associate','staff'],['kino','Kino','Sales Associate','staff']] as const;
const normalize=(s:string)=>s.trim().toLowerCase().replace(/\s+/g,' ');
export function exactProduct(a:Detail['product'],b:Product){return (['year','set','sport','format'] as const).every(k=>Boolean(a[k])&&normalize(a[k])===normalize(b[k]));}
export function rankStory(item:{title:string;summary:string;kind:string;published_at:string|null},d:Detail|undefined,products:Product[],now=new Date()){
 const reasons:{points:number;reason:string}[]=[];const add=(points:number,reason:string)=>reasons.push({points,reason});
 const match=d&&products.find(p=>exactProduct(d.product,p)&&['carried','incoming'].includes(p.status));
 if(match)add(100,`Exact product match: ${match.status}, confirmed ${match.confirmedAt}. This is not a live stock check.`);
 const content=(item.title+' '+item.summary).toLowerCase();
 if(d&&['release','checklist','delay','official announcement'].includes(d.topic))add(50,`Staff tagged ${d.topic}`);else if(item.kind==='release'||/\b(release|checklist|delay|announcement)\b/.test(content))add(30,'Release or checklist signal in source text; needs verification');
 if(d?.topic==='chase'||item.kind==='chase'||/\b(1\/1|superfractor|debut patch|rookie auto|ssp|case hit|illustration rare)\b/.test(content))add(25,'Chase card signal');
 if(d?.topic==='pull')add(15,'Staff tagged notable pull');if(d?.saleType==='completed')add(15,'Staff recorded completed sale');
 if(/\b(chicago|bears|bulls|cubs|white sox|blackhawks|packers|rockford|regional show|collector event)\b/i.test((d?.region||'')+' '+content))add(10,'Local team or collector community relevance');
 if(d?.certainty==='confirmed')add(5,'Staff confirmed with source');if(d?.certainty==='rumor')add(-20,'Rumor: verify before using');
 if(item.published_at){const age=(now.getTime()-Date.parse(item.published_at))/86400000;if(age>=0&&age<=14)add(5,'Published in the past 14 days');}
 return {score:reasons.reduce((n,r)=>n+r.points,0),reasons,availability:match?`${match.status} · ${match.confirmedAt}`:'Availability not confirmed',certainty:d?.certainty||'incomplete'};
}
